### ISSUE TITLE
DO EVERYTHING

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/12urenloop#147]
**Dinsdag 12/4**
- [x] Afspreken met Leander (#128)
- [x] Router instellen (#90)
- [x] Manueel telsysteem testen (#97)

**Woensdag 13/4**
- [x] Sponsors, speciale rondes en DJs updaten (#129)
- [x] Telsystemen updaten met nieuwe kringen (#132)
- [x] Testrun doen (#96)
- [x] Koop dingen (#126)

**Donderdag 14/4**
- [x] DJ-voting systeem testen (#87)
- [x] Stokken testen (#130)
- [x] Kabels testen (#130)
- [x] Mac-addressen v/d stokken checken

**Vrijdag 15/4**
- [x] Batterijen opladen

**Zondag 17/4**
- [x] Snapchatding opzetten (#127)
- [ ] ~~Kaartje van plein op live.12urenloop.be zetten (#140)~~
- [x] Saruman afwerken

**Maandag 18/4**
- [x] Ophalen laptops van DICT (#91)
- [x] Al het materiaal klaarzetten (#133)

**Dinsdag 19/4**
- [x] Alles naar Yachtdreef vervoeren (#133)
- [x] Container organiseren
- [x] Netwerk leggen (van aankomsttoren naar onze container)
- [x] Wanneer Urgent-container er is: netwerk naar Urgent
- [x] Wanneer stockcontainer er is: netwerk naar stockcontainer
- [x] Eventueel al netwerk telsysteem leggen

**Woensdag 20/4**
- [x] Netwerk telsysteem leggen
- [x] Telsysteem testen
- [x] Boxxy testen (+ wachtwoord aanpassen)
- [x] Materiaalsysteem testen
- [x] Test DJ-rating system again
- [x] Test freezing van Boxxy
- [ ] ~~Twitterwall testen (#75)~~
- [ ] ~~Backup-4G-router testen~~
- [x] Batterijen laatste keer opladen

**Donderdag 21/4**
- [x] 7h45: Assemblage stokken
- [x] 8h15: Gyrids buiten zetten, aansluiten, laatste test
- [x] 8h45: Briefing Zeus
- [x] 8h50: Resetten databases telsysteem, manual count en DJ contest
- [x] 9h00: Handmatig tellen eerste uur (2/3 mensen)
- [x] `tail -f syslog` van alle gyrids
- [x] Heel de dag: timeline updaten (@R13N)
- [x] 20h: Freeze Boxxy
- [x] 20h45: Zeus briefing about afbraak
- [x] DJ-resultaten rapporteren (inclusief Facebook-likes)
- [x] 21h: Afbraak deel 1 (stokken, gyrids en netwerk telsysteem binnenhalen; container opruimen)
- [x] 22h45: Unfreeze boxxy + dj-contest online
- [x] 23h: Afbraak deel 2 (netwerk naar Urgent/Schamper weghalen; afbraak plein)
- [x] na 2h: Afbraak deel 3 (netwerk naar containers+materiaaltent weg; netwerk uplink weg)

**Vrijdag 22/4**
- [ ] Afbraak deel 4

**Comment by Procrat** [comment]
Yaay
