### ISSUE TITLE
Tiny to-do tasks

### ISSUE THREAD

**Issue by TomNaessens** [ZeusWPI/12urenloop#71]
Vooraf:
- [x] Bestellen extra materiaal Gotron (asap, Tom Naessens)
- [x] De stokjes moeten worden gesoldeerd, hermaakt, etc. (WOENSDAG 16 APRIL)
- [x] Instellen gyridnetwerk en testen STP (tegen vrijdag 18 april, Tom Naessens)
- [x] Token moet voorzien worden van Gnokii of Gammu (ik geloof dat ik vorig jaar Gammu heb gebruikt) om de SMSjes van de DJ-contest te ontvangen en bij te houden in een databees (tegen vrijdag 25 april)
- [x] Regelen walkies (asap, Tom Naessens)
- [x] Instellen van de IP camera met een RPi (hoe verloopt de output hier?) zodat we onze IP camera kunnen besturen vanop afstand (wie heeft dit vorig jaar gedaan?) (tegen vrijdag 25 april, Wouter en Stefaan)
- [x] Fixen van CVC voor het nieuwe protocol (tegen vrijdag 18 april, @FelixVanderJeugt )
- [x] Testen van het handmatig telsysteem en bijwerken voor de nieuwe loopteams (tegen vrijdag 25 april, best iemand met een iPad)
- [x] Regelen videomateriaal (asap, Tom Naessens)
- [x] IKEA: batterijen en doosklemmen (tegen vrijdag 25 april, Tom Naessens)
- [x] Testen en klaarmaken van Boxxy (tegen vrijdag 25 april, @FelixVanderJeugt / @Procrat )
- [x] Voorbereiden van netwerk: VLANs, rate limits, Token, etc. Met iets van info of plan oid (tegen vrijdag 25 april, @nudded )
- [x] Afwerken Saruman (scansysteem) (tegen vrijdag 25 april, @Silox)
- [x] Opladen SIM-kaart voor geldigheid (of nieuwe sim met herkenbaar nummer) @stefaanvermassen
- [x] Updaten van sponsor-powerpoint met nieuwe sponsors (meer info te verkrijgen bij @silox)
- [x] De website moet worden geprepareerd met D3-visuaties zoals vorig jaar

Maandag:
- [x] Ophalen batterijen (Roel)
- [x] Ophalen PCs en Laptop (DICT)
- [x] Installeren van alle PCs die we van DICT krijgen (Dropbox, wallpaper) (We krijgen deze maandagochtend 28 april, dus dit is een last-minute job, Wouter en Stefaan)
- [x] Alles verzamelen en inladen
- [x] Testen stokken mac adressen
- [x] Container organiseren en netwerk leggen in container (Javache)
- [x] Internet via Abdij leggen (Javache, Toon)

Dinsdag:
- [x] Ophalen videomateriaal (camera, statief, monitors, coax voor monitors) DICT
- [x] Levering walkies (plein)
- [x] Levering ledwall (plein)
- [x] Levering videocaptatie (plein)
- [x] Testen telsysteem
- [x] Testen + uitleg materiaalbeheersysteem

Woensdag:
- [x] Resetten databases telsysteem, manual count en DJ contest
- [x] Assemblage stokken
- [x] Gyrids buiten zetten, aansluiten, laatste test
- [x] Briefing Zeus
- [x] Handmatig tellen eerste ~uur
- [x] Permanentie hele dag
- [x] Freeze Boxxy!
- [x] Bereken scores DJ contest
- [x] Afbraak afbraak afbraak
